// src/renderer/src/components/explorer/FileTreeItem.vue
<script setup lang="ts">
import { FileItem } from '@fixtures/file';
import { useExplorerStore } from '@renderer/store/explorer';
import 'material-icons/iconfont/material-icons.css';
import { storeToRefs } from 'pinia';
import { computed, inject, nextTick, ref, watch, type Ref } from 'vue';

type NewEntryMode = 'file' | 'directory';

type NewEntryState = {
  isActive: boolean;
  mode: NewEntryMode;
  parentPath: string | null;
  name: string;
};

type NewEntryContext = {
  state: Ref<NewEntryState>;
  confirm: () => Promise<void>;
  cancel: () => void;
};

type RenameEntryState = {
  isActive: boolean;
  targetPath: string | null;
  name: string;
};

type RenameEntryContext = {
  state: Ref<RenameEntryState>;
  confirm: () => Promise<void>;
  cancel: () => void;
};

const props = defineProps<{
  item: FileItem;
}>();

const store = useExplorerStore();
const { selectedPath, selectedDirPath, expandPaths } = storeToRefs(store);

const isExpand = computed(() => {
  return expandPaths.value.has(props.item.path);
});

const isSelected = computed(() => {
  return props.item.path === (selectedPath.value ?? selectedDirPath.value);
});

const newEntry = inject<NewEntryContext | null>('newEntry', null);
const renameEntry = inject<RenameEntryContext | null>('renameEntry', null);
const inputRef = ref<HTMLInputElement | null>(null);
const renameInputRef = ref<HTMLInputElement | null>(null);

const shouldShowNewEntryHere = computed(() => {
  if (!newEntry?.state.value.isActive) return false;
  return newEntry.state.value.parentPath === props.item.path;
});

const shouldShowRenameHere = computed(() => {
  if (!renameEntry?.state.value.isActive) return false;
  return renameEntry.state.value.targetPath === props.item.path;
});

watch(
  () => shouldShowNewEntryHere.value,
  async (visible) => {
    if (visible) {
      await nextTick();
      inputRef.value?.focus();
      inputRef.value?.select();
    }
  }
);

watch(
  () => shouldShowRenameHere.value,
  async (visible) => {
    if (visible) {
      await nextTick();
      renameInputRef.value?.focus();
      renameInputRef.value?.select();
    }
  }
);

const handleClick = (): void => {
  if (props.item.isDirectory) {
    store.selectedPath = null;
    store.selectedDirPath = props.item.path;
    if (isExpand.value) store.expandPaths.delete(props.item.path);
    else store.expandPaths.add(props.item.path);
  } else {
    store.selectedDirPath = null;
    store.selectedPath = props.item.path;
  }
};

const onNewEntryKeydown = async (event: KeyboardEvent): Promise<void> => {
  if (!newEntry) return;
  if (event.key === 'Enter') {
    event.preventDefault();
    await newEntry.confirm();
  } else if (event.key === 'Escape') {
    event.preventDefault();
    newEntry.cancel();
  }
};

const onRenameKeydown = async (event: KeyboardEvent): Promise<void> => {
  if (!renameEntry) return;
  if (event.key === 'Enter') {
    event.preventDefault();
    await renameEntry.confirm();
  } else if (event.key === 'Escape') {
    event.preventDefault();
    renameEntry.cancel();
  }
};
</script>

<template>
  <li>
    <div
      class="file-tree-item"
      :class="{ 'file-item-is-selected': isSelected }"
      @click="handleClick"
    >
      <span
        v-if="props.item.isDirectory"
        class="material-icons-round file-item-chevron"
        :class="{ 'file-item-chevron-expand': isExpand }"
        >chevron_right</span
      >
      <span v-if="props.item.isDirectory" class="material-icons file-item-folder">
        {{ isExpand ? 'folder_open' : 'folder' }}
      </span>
      <input
        v-if="shouldShowRenameHere"
        ref="renameInputRef"
        v-model="renameEntry!.state.value.name"
        class="file-item-new-input"
        @keydown="onRenameKeydown"
        @blur="renameEntry!.cancel"
      />
      <p
        v-else
        class="file-item-name"
        :class="{ 'file-item-not-directory': !props.item.isDirectory }"
      >
        {{ props.item.name }}
      </p>
    </div>
    <ul v-if="props.item.isDirectory && props.item.children && isExpand" class="file-item-children">
      <li v-if="shouldShowNewEntryHere" class="file-item-new">
        <div class="file-tree-item">
          <span class="material-icons-round file-item-chevron file-item-icon-placeholder"
            >chevron_right</span
          >
          <span
            class="material-icons file-item-folder"
            :class="{ 'file-item-icon-placeholder': newEntry?.state.value.mode !== 'directory' }"
            >folder</span
          >
          <input
            ref="inputRef"
            v-model="newEntry!.state.value.name"
            class="file-item-new-input"
            @keydown="onNewEntryKeydown"
            @blur="newEntry!.cancel"
          />
        </div>
      </li>
      <FileTreeItem v-for="child in props.item.children" :key="child.path" :item="child" />
    </ul>
  </li>
</template>

<style>
.file-item-folder {
  color: var(--folder);
  font-size: 12px;
}

.file-item-chevron {
  font-size: 12px;
}

.file-item-chevron-expand {
  transform: rotate(90deg);
}

.file-tree-item {
  display: flex;
  align-items: center;
  gap: 2px;
  cursor: pointer;
}

.file-item-name {
  margin: 0;
}

.file-item-not-directory {
  padding-left: 28px;
}

.file-item-children {
  list-style-type: none;
  margin: 0;
  padding: 0 0 0 12px;
}

.file-item-is-selected {
  background-color: var(--main-light);
}

.file-item-new {
  list-style-type: none;
}

.file-item-new-input {
  width: 100%;
  min-width: 0;
}

.file-item-icon-placeholder {
  visibility: hidden;
}
</style>

// src/renderer/src/features/explorer/FileTreeItem.tsx
import { useEffect, useRef } from 'react';
import type { FileItem } from '@shared/types/file';
import { useAppDispatch, useAppSelector } from '@renderer/app/hooks';
import { useActiveWorkspaceApi } from '@renderer/features/workspace/useActiveWorkspaceApi';
import type { NewEntryState, RenameEntryState } from './FileTree';
import { selectDirectory, selectFile } from './explorerSlice';

interface FileTreeItemProps {
  item: FileItem;
  newEntry: NewEntryState;
  renameEntry: RenameEntryState;
  onNewEntryNameChange: (name: string) => void;
  onRenameEntryNameChange: (name: string) => void;
  onConfirmNewEntry: () => Promise<void>;
  onCancelNewEntry: () => void;
  onConfirmRenameEntry: () => Promise<void>;
  onCancelRenameEntry: () => void;
}

export const FileTreeItem = ({
  item,
  newEntry,
  renameEntry,
  onNewEntryNameChange,
  onRenameEntryNameChange,
  onConfirmNewEntry,
  onCancelNewEntry,
  onConfirmRenameEntry,
  onCancelRenameEntry
}: FileTreeItemProps): React.JSX.Element => {
  const dispatch = useAppDispatch();
  const workspaceApi = useActiveWorkspaceApi();
  const newEntryInputRef = useRef<HTMLInputElement | null>(null);
  const renameInputRef = useRef<HTMLInputElement | null>(null);
  const { selectedPath, selectedDirPath, expandedPaths } = useAppSelector(
    (state) => state.explorer
  );

  const isExpanded = expandedPaths.includes(item.path);
  const isSelected = item.path === (selectedPath ?? selectedDirPath);
  const shouldShowNewEntryHere = newEntry.isActive && newEntry.parentPath === item.path;
  const shouldShowRenameHere = renameEntry.isActive && renameEntry.targetPath === item.path;

  useEffect(() => {
    if (!shouldShowNewEntryHere) return;
    newEntryInputRef.current?.focus();
    newEntryInputRef.current?.select();
  }, [shouldShowNewEntryHere]);

  useEffect(() => {
    if (!shouldShowRenameHere) return;
    renameInputRef.current?.focus();
    renameInputRef.current?.select();
  }, [shouldShowRenameHere]);

  const handleClick = async (): Promise<void> => {
    if (item.isDirectory) {
      dispatch(selectDirectory(item.path));
      return;
    }

    dispatch(selectFile(item.path));
    await workspaceApi.openFile(item.path);
  };

  const onNewEntryKeyDown = (event: React.KeyboardEvent<HTMLInputElement>): void => {
    event.stopPropagation();
    if (event.key === 'Enter') {
      event.preventDefault();
      onConfirmNewEntry().catch((error: unknown) => {
        console.error('Failed to create entry', error);
      });
    } else if (event.key === 'Escape') {
      event.preventDefault();
      onCancelNewEntry();
    }
  };

  const onRenameKeyDown = (event: React.KeyboardEvent<HTMLInputElement>): void => {
    event.stopPropagation();
    if (event.key === 'Enter') {
      event.preventDefault();
      onConfirmRenameEntry().catch((error: unknown) => {
        console.error('Failed to rename entry', error);
      });
    } else if (event.key === 'Escape') {
      event.preventDefault();
      onCancelRenameEntry();
    }
  };

  return (
    <li>
      <div
        className={`file-tree-item ${isSelected ? 'file-item-is-selected' : ''}`}
        role="button"
        tabIndex={0}
        onClick={() => {
          handleClick().catch((error: unknown) => {
            console.error('Failed to open file tree item', error);
          });
        }}
        onKeyDown={(event) => {
          if (event.key !== 'Enter' && event.key !== ' ') return;
          event.preventDefault();
          handleClick().catch((error: unknown) => {
            console.error('Failed to open file tree item', error);
          });
        }}
      >
        {item.isDirectory ? (
          <>
            <span
              className={`material-icons-round file-item-chevron ${
                isExpanded ? 'file-item-chevron-expand' : ''
              }`}
            >
              chevron_right
            </span>
            <span className="material-icons file-item-folder">
              {isExpanded ? 'folder_open' : 'folder'}
            </span>
          </>
        ) : null}
        {shouldShowRenameHere ? (
          <input
            ref={renameInputRef}
            className="file-item-new-input"
            value={renameEntry.name}
            onClick={(event) => event.stopPropagation()}
            onChange={(event) => onRenameEntryNameChange(event.target.value)}
            onKeyDown={onRenameKeyDown}
            onBlur={onCancelRenameEntry}
          />
        ) : (
          <p className={`file-item-name ${item.isDirectory ? '' : 'file-item-not-directory'}`}>
            {item.name}
          </p>
        )}
      </div>
      {item.isDirectory && item.children && isExpanded ? (
        <ul className="file-item-children">
          {shouldShowNewEntryHere ? (
            <li className="file-item-new">
              <div className="file-tree-item">
                <span className="file-item-chevron material-icons-round file-item-icon-placeholder">
                  chevron_right
                </span>
                <span
                  className={`file-item-folder material-icons ${
                    newEntry.mode !== 'directory' ? 'file-item-icon-placeholder' : ''
                  }`}
                >
                  folder
                </span>
                <input
                  ref={newEntryInputRef}
                  className="file-item-new-input"
                  value={newEntry.name}
                  onChange={(event) => onNewEntryNameChange(event.target.value)}
                  onKeyDown={onNewEntryKeyDown}
                  onBlur={onCancelNewEntry}
                />
              </div>
            </li>
          ) : null}
          {item.children.map((child) => (
            <FileTreeItem
              key={child.path}
              item={child}
              newEntry={newEntry}
              renameEntry={renameEntry}
              onNewEntryNameChange={onNewEntryNameChange}
              onRenameEntryNameChange={onRenameEntryNameChange}
              onConfirmNewEntry={onConfirmNewEntry}
              onCancelNewEntry={onCancelNewEntry}
              onConfirmRenameEntry={onConfirmRenameEntry}
              onCancelRenameEntry={onCancelRenameEntry}
            />
          ))}
        </ul>
      ) : null}
    </li>
  );
};
